"""
Agent 2: Excel Workbook Builder

Takes a FinancialData object and produces a professional .xlsx workbook with:
  Sheet 1  — Cover
  Sheet 2  — Income Statement  (IS)
  Sheet 3  — Balance Sheet     (BS)
  Sheet 4  — Cash Flow         (CF)
  Sheet 5  — Ratios
  Sheet 6  — Verification
  Sheet 7  — Settings
  Sheet 8  — WACC & Cost of Capital
  Sheet 9  — DCF Valuation
  Sheet 10 — DDM Valuation
  Sheet 11 — Comparable Company Analysis (Comps)

All computed cells are written as LIVE Excel formulas, not hardcoded values.
Raw extracted values are written as numbers and referenced by formulas.
"""
from datetime import datetime
from pathlib import Path
from typing import List, Optional

import xlsxwriter

from config.settings import (
    CORPORATE_TAX_RATE,
    DEFAULT_BETA,
    EQUITY_RISK_PREMIUM,
    EXCEL_DIR,
    RISK_FREE_RATE,
    TERMINAL_GROWTH_RATE,
)
from models.company_data import FinancialData
from models.financial_statements import BalanceSheet, CashFlowStatement, IncomeStatement
from utils.excel_styles import StyleBook
from utils.formula_registry import (
    balance_check,
    cagr,
    cash_conversion_cycle,
    closing_cash,
    col_letter,
    days_formula,
    dupont_roe,
    ebit,
    ebit_margin,
    ebitda_margin,
    effective_tax_rate,
    eps,
    free_cash_flow,
    gross_margin,
    gross_profit,
    net_change_in_cash,
    net_debt,
    net_fixed_assets,
    net_margin,
    pat,
    pbt,
    payout_ratio,
    ratio_formula,
    sum_range,
    total_assets,
    total_income,
    total_liabilities,
    total_liabilities_and_equity,
    working_capital,
    xref,
    yoy_growth,
)
from utils.logger import get_logger

log = get_logger()

# ── Sheet name constants (used for cross-references) ─────────────────────────
SH_IS  = "Income Statement"
SH_BS  = "Balance Sheet"
SH_CF  = "Cash Flow"
SH_RT  = "Ratios"
SH_VR  = "Verification"
SH_ST  = "Settings"
SH_WC  = "WACC"
SH_DCF = "DCF Valuation"
SH_DDM = "DDM Valuation"
SH_CMP = "Comps"


def _write_val(ws, row: int, col: int, value, fmt=None):
    """Write a number or None (skip None to leave cell empty)."""
    if value is None:
        return
    if fmt:
        ws.write_number(row, col, value, fmt)
    else:
        ws.write_number(row, col, value)


def _data_cols(years: List[int]) -> List[int]:
    """Return 0-based column indices for each year's data (starting at col 1 = B)."""
    return [i + 1 for i in range(len(years))]


# ── Sheet: Cover ──────────────────────────────────────────────────────────────

def _build_cover(wb: xlsxwriter.Workbook, sty: StyleBook,
                 company: str, years: List[int]):
    ws = wb.add_worksheet("Cover")
    ws.hide_gridlines(2)
    ws.set_column(0, 7, 14)
    ws.set_row(0, 20)
    ws.set_row(2, 50)
    ws.set_row(4, 30)
    ws.set_row(6, 25)

    ws.merge_range("A3:H3", company, sty.cover_title)
    ws.merge_range("A4:H4", "Financial Analysis Report", sty.cover_sub)
    ws.merge_range("A5:H5",
                   f"Fiscal Years: {' | '.join(str(y) for y in sorted(years))}",
                   sty.cover_body)

    # Table of Contents
    ws.write("A8", "Contents", sty.subtitle)
    sheets = [
        (SH_IS,  "Income Statement (Profit & Loss)"),
        (SH_BS,  "Balance Sheet"),
        (SH_CF,  "Cash Flow Statement"),
        (SH_RT,  "Financial Ratios & Analysis"),
        (SH_VR,  "Verification & Quality Checks"),
        (SH_ST,  "Settings & Assumptions"),
        (SH_WC,  "WACC & Cost of Capital"),
        (SH_DCF, "DCF Valuation (5-Year FCF Model)"),
        (SH_DDM, "DDM Valuation (Dividend Discount)"),
        (SH_CMP, "Comparable Company Analysis"),
        ("Charts","Charts & Visualisations"),
    ]
    for i, (sheet, label) in enumerate(sheets):
        ws.write_url(f"A{9+i}", f"internal:'{sheet}'!A1", sty.cover_link, label)

    # Footer
    ts = datetime.now().strftime("%B %d, %Y %H:%M")
    ws.merge_range(f"A{16}:H{16}",
                   f"Generated by Financial Analysis AI  ·  {ts}",
                   sty.cover_footer)
    return ws


# ── Sheet: Income Statement ───────────────────────────────────────────────────

# Row map for IS (1-based)
IS = {
    "header":        1,
    "revenue":       3,
    "other_income":  4,
    "total_income":  5,
    # Cost
    "cost_hdr":      7,
    "cogs":          8,
    "employee":      9,
    "other_opex":    10,
    "total_opex":    11,
    # Profitability
    "prof_hdr":      13,
    "gross_profit":  14,
    "gross_margin":  15,
    "ebitda":        16,
    "ebitda_margin": 17,
    "da":            18,
    "ebit":          19,
    "ebit_margin":   20,
    "interest":      21,
    "pbt":           22,
    "tax":           23,
    "eff_tax":       24,
    "pat":           25,
    "net_margin":    26,
    # Per share
    "pershare_hdr":  28,
    "shares":        29,
    "eps":           30,
    "dps":           31,
    "payout":        32,
}


def _build_is(wb: xlsxwriter.Workbook, sty: StyleBook,
              statements: List[IncomeStatement], years: List[int]):
    ws = wb.add_worksheet(SH_IS)
    ws.freeze_panes(2, 1)
    ws.hide_gridlines(2)
    ws.set_column(0, 0, 32)   # Labels

    n = len(years)
    data_cols = _data_cols(years)  # [1, 2, 3] → cols B, C, D

    # Year columns
    for i, yr in enumerate(years):
        ws.set_column(data_cols[i], data_cols[i], 14)
        ws.write(0, data_cols[i], str(yr), sty.col_header)

    # YoY and CAGR columns
    yoy_start = data_cols[-1] + 1
    for i in range(n - 1):
        c = yoy_start + i
        ws.set_column(c, c, 12)
        if i + 1 < n:
            ws.write(0, c, f"YoY {years[i]}→{years[i+1]}", sty.col_header_gold)
    cagr_col = yoy_start + max(n - 1, 0)
    if n > 1:
        ws.set_column(cagr_col, cagr_col, 12)
        ws.write(0, cagr_col, f"CAGR {years[0]}→{years[-1]}", sty.col_header_gold)

    def lbl(row: int, text: str, fmt=None):
        ws.write(row - 1, 0, text, fmt or sty.line_label)

    def val(row: int, col_idx: int, value, fmt=None):
        _write_val(ws, row - 1, col_idx, value, fmt or sty.num)

    def fml(row: int, col_idx: int, formula: str, fmt=None):
        ws.write_formula(row - 1, col_idx, formula, fmt or sty.num)

    def xc(col_idx: int) -> str:
        return col_letter(col_idx + 1)  # 0-based col → Excel letter

    # ── Labels ────────────────────────────────────────────────────────────────
    ws.write(IS["header"] - 1, 0, "INCOME STATEMENT", sty.col_header)

    lbl(IS["revenue"], "Net Revenue / Net Sales")
    lbl(IS["other_income"], "Other Income")
    lbl(IS["total_income"], "Total Income", sty.subtotal_label)

    lbl(IS["cost_hdr"], "COST STRUCTURE", sty.section_label)
    lbl(IS["cogs"], "Cost of Revenue / COGS")
    lbl(IS["employee"], "Employee Expenses")
    lbl(IS["other_opex"], "Other Operating Expenses")
    lbl(IS["total_opex"], "Total Operating Expenses", sty.subtotal_label)

    lbl(IS["prof_hdr"], "PROFITABILITY", sty.section_label)
    lbl(IS["gross_profit"], "Gross Profit", sty.subtotal_label)
    lbl(IS["gross_margin"], "  Gross Margin %")
    lbl(IS["ebitda"], "EBITDA", sty.subtotal_label)
    lbl(IS["ebitda_margin"], "  EBITDA Margin %")
    lbl(IS["da"], "Depreciation & Amortisation")
    lbl(IS["ebit"], "EBIT (Operating Profit)", sty.subtotal_label)
    lbl(IS["ebit_margin"], "  EBIT Margin %")
    lbl(IS["interest"], "Interest / Finance Costs")
    lbl(IS["pbt"], "Profit Before Tax (PBT)", sty.subtotal_label)
    lbl(IS["tax"], "Tax Expense")
    lbl(IS["eff_tax"], "  Effective Tax Rate %")
    lbl(IS["pat"], "NET PROFIT (PAT)", sty.subtotal_label)
    lbl(IS["net_margin"], "  Net Margin %")

    lbl(IS["pershare_hdr"], "PER SHARE DATA", sty.section_label)
    lbl(IS["shares"], "Shares Outstanding (Mn)")
    lbl(IS["eps"], "EPS (Basic)", sty.subtotal_label)
    lbl(IS["dps"], "Dividends Per Share")
    lbl(IS["payout"], "  Payout Ratio %")

    # ── Values and Formulas per Year ──────────────────────────────────────────
    for i, (yr, stmt) in enumerate(zip(years, statements)):
        c = data_cols[i]
        cx = xc(c)

        # Raw values (extracted)
        val(IS["revenue"], c, stmt.revenue)
        val(IS["other_income"], c, stmt.other_income)
        val(IS["cogs"], c, stmt.cogs)
        val(IS["employee"], c, stmt.employee_expenses)
        val(IS["other_opex"], c, stmt.other_operating_expenses)
        val(IS["da"], c, stmt.depreciation_amortization)
        val(IS["interest"], c, stmt.interest_expense)
        val(IS["tax"], c, stmt.tax_expense)
        val(IS["shares"], c, stmt.shares_outstanding, sty.num_int)
        val(IS["dps"], c, stmt.dividends_per_share)

        # EBITDA — use extracted if available, else compute
        if stmt.ebitda is not None:
            val(IS["ebitda"], c, stmt.ebitda, sty.num_sub)
        elif stmt.revenue is not None and stmt.cogs is not None:
            # approximate: revenue - opex components (no DA yet)
            val(IS["ebitda"], c, stmt.ebitda, sty.num_sub)

        # PAT — use extracted if available
        if stmt.pat is not None:
            val(IS["pat"], c, stmt.pat, sty.num_sub)

        # PBT — use extracted if available
        if stmt.pbt is not None:
            val(IS["pbt"], c, stmt.pbt, sty.num_sub)

        # Computed formulas
        fml(IS["total_income"], c, total_income(cx, cx, IS["other_income"])
            .replace(f"{cx}{IS['other_income']}", f"{cx}{IS['other_income']}"), sty.num_sub)

        fml(IS["gross_profit"], c,
            gross_profit(IS["revenue"], IS["cogs"], cx), sty.num_sub)
        fml(IS["gross_margin"], c,
            gross_margin(IS["gross_profit"], IS["revenue"], cx), sty.pct)
        fml(IS["ebitda_margin"], c,
            ebitda_margin(IS["ebitda"], IS["revenue"], cx), sty.pct)
        fml(IS["ebit"], c,
            ebit(IS["ebitda"], IS["da"], cx), sty.num_sub)
        fml(IS["ebit_margin"], c,
            ebit_margin(IS["ebit"], IS["revenue"], cx), sty.pct)
        fml(IS["eff_tax"], c,
            effective_tax_rate(IS["tax"], IS["pbt"], cx), sty.pct)
        fml(IS["net_margin"], c,
            net_margin(IS["pat"], IS["revenue"], cx), sty.pct)
        fml(IS["eps"], c,
            eps(IS["pat"], IS["shares"], cx), sty.num_sub)
        fml(IS["payout"], c,
            payout_ratio(IS["dps"], IS["eps"], cx), sty.pct)

    # ── YoY Growth Columns ────────────────────────────────────────────────────
    growth_rows = [IS["revenue"], IS["ebitda"], IS["ebit"], IS["pat"]]
    for i in range(n - 1):
        yc = yoy_start + i
        prev_cx = xc(data_cols[i])
        curr_cx = xc(data_cols[i + 1])
        for r in growth_rows:
            fml(r, yc, yoy_growth(curr_cx, prev_cx, r), sty.pct_growth_pos)

    # ── CAGR Column ───────────────────────────────────────────────────────────
    if n > 1:
        start_cx = xc(data_cols[0])
        end_cx = xc(data_cols[-1])
        periods = n - 1
        for r in growth_rows:
            fml(r, cagr_col, cagr(end_cx, start_cx, r, periods), sty.pct_growth_pos)

    return ws


# ── Sheet: Balance Sheet ──────────────────────────────────────────────────────

BS = {
    "header":         1,
    # Current Assets
    "ca_hdr":         2,
    "cash":           3,
    "sti":            4,
    "receivables":    5,
    "inventory":      6,
    "other_ca":       7,
    "total_ca":       8,
    # Non-Current Assets
    "nca_hdr":        10,
    "gross_fa":       11,
    "acc_dep":        12,
    "net_fa":         13,
    "cwip":           14,
    "intangibles":    15,
    "goodwill":       16,
    "lt_invest":      17,
    "other_nca":      18,
    "total_nca":      19,
    "total_assets":   20,
    # Current Liabilities
    "cl_hdr":         22,
    "st_borr":        23,
    "payables":       24,
    "other_cl":       25,
    "total_cl":       26,
    # Non-Current Liabilities
    "ncl_hdr":        28,
    "lt_debt":        29,
    "dt_liab":        30,
    "other_ncl":      31,
    "total_ncl":      32,
    "total_liab":     33,
    # Equity
    "eq_hdr":         35,
    "share_cap":      36,
    "reserves":       37,
    "mi":             38,
    "total_equity":   39,
    "total_le":       40,
    # Checks
    "balance_check":  42,
    "wc":             43,
    "net_debt":       44,
}


def _build_bs(wb: xlsxwriter.Workbook, sty: StyleBook,
              statements: List[BalanceSheet], years: List[int]):
    ws = wb.add_worksheet(SH_BS)
    ws.freeze_panes(2, 1)
    ws.hide_gridlines(2)
    ws.set_column(0, 0, 32)

    data_cols = _data_cols(years)
    for i, yr in enumerate(years):
        ws.set_column(data_cols[i], data_cols[i], 14)
        ws.write(0, data_cols[i], str(yr), sty.col_header)

    def lbl(row: int, text: str, fmt=None):
        ws.write(row - 1, 0, text, fmt or sty.line_label)

    def val(row: int, col_idx: int, value, fmt=None):
        _write_val(ws, row - 1, col_idx, value, fmt or sty.num)

    def fml(row: int, col_idx: int, formula: str, fmt=None):
        ws.write_formula(row - 1, col_idx, formula, fmt or sty.num)

    def xc(col_idx: int) -> str:
        return col_letter(col_idx + 1)

    ws.write(BS["header"] - 1, 0, "BALANCE SHEET", sty.col_header)

    # ── Labels ────────────────────────────────────────────────────────────────
    lbl(BS["ca_hdr"], "CURRENT ASSETS", sty.section_label)
    lbl(BS["cash"], "Cash & Cash Equivalents")
    lbl(BS["sti"], "Short-Term Investments")
    lbl(BS["receivables"], "Trade Receivables / Debtors")
    lbl(BS["inventory"], "Inventories")
    lbl(BS["other_ca"], "Other Current Assets")
    lbl(BS["total_ca"], "TOTAL CURRENT ASSETS", sty.subtotal_label)

    lbl(BS["nca_hdr"], "NON-CURRENT ASSETS", sty.section_label)
    lbl(BS["gross_fa"], "Gross Fixed Assets (Gross Block)")
    lbl(BS["acc_dep"], "Less: Accumulated Depreciation")
    lbl(BS["net_fa"], "Net Fixed Assets (Net Block)", sty.subtotal_label)
    lbl(BS["cwip"], "Capital Work-in-Progress")
    lbl(BS["intangibles"], "Intangible Assets")
    lbl(BS["goodwill"], "Goodwill")
    lbl(BS["lt_invest"], "Long-Term Investments")
    lbl(BS["other_nca"], "Other Non-Current Assets")
    lbl(BS["total_nca"], "TOTAL NON-CURRENT ASSETS", sty.subtotal_label)
    lbl(BS["total_assets"], "TOTAL ASSETS", sty.subtotal_label)

    lbl(BS["cl_hdr"], "CURRENT LIABILITIES", sty.section_label)
    lbl(BS["st_borr"], "Short-Term Borrowings")
    lbl(BS["payables"], "Trade Payables / Creditors")
    lbl(BS["other_cl"], "Other Current Liabilities")
    lbl(BS["total_cl"], "TOTAL CURRENT LIABILITIES", sty.subtotal_label)

    lbl(BS["ncl_hdr"], "NON-CURRENT LIABILITIES", sty.section_label)
    lbl(BS["lt_debt"], "Long-Term Debt / Borrowings")
    lbl(BS["dt_liab"], "Deferred Tax Liabilities")
    lbl(BS["other_ncl"], "Other Non-Current Liabilities")
    lbl(BS["total_ncl"], "TOTAL NON-CURRENT LIABILITIES", sty.subtotal_label)
    lbl(BS["total_liab"], "TOTAL LIABILITIES", sty.subtotal_label)

    lbl(BS["eq_hdr"], "SHAREHOLDERS' EQUITY", sty.section_label)
    lbl(BS["share_cap"], "Share Capital (Paid-up)")
    lbl(BS["reserves"], "Reserves & Surplus")
    lbl(BS["mi"], "Minority / Non-Controlling Interest")
    lbl(BS["total_equity"], "TOTAL EQUITY", sty.subtotal_label)
    lbl(BS["total_le"], "TOTAL LIABILITIES + EQUITY", sty.subtotal_label)

    lbl(BS["balance_check"], "Balance Sheet Check", sty.section_label)
    lbl(BS["wc"], "Working Capital")
    lbl(BS["net_debt"], "Net Debt")

    # ── Values and Formulas ───────────────────────────────────────────────────
    for i, (yr, stmt) in enumerate(zip(years, statements)):
        c = data_cols[i]
        cx = xc(c)

        val(BS["cash"], c, stmt.cash_and_equivalents)
        val(BS["sti"], c, stmt.short_term_investments)
        val(BS["receivables"], c, stmt.accounts_receivable)
        val(BS["inventory"], c, stmt.inventory)
        val(BS["other_ca"], c, stmt.other_current_assets)

        val(BS["gross_fa"], c, stmt.gross_fixed_assets)
        val(BS["acc_dep"], c, stmt.accumulated_depreciation)
        val(BS["cwip"], c, stmt.capital_wip)
        val(BS["intangibles"], c, stmt.intangible_assets)
        val(BS["goodwill"], c, stmt.goodwill)
        val(BS["lt_invest"], c, stmt.long_term_investments)
        val(BS["other_nca"], c, stmt.other_non_current_assets)

        val(BS["st_borr"], c, stmt.short_term_borrowings)
        val(BS["payables"], c, stmt.accounts_payable)
        val(BS["other_cl"], c, stmt.other_current_liabilities)

        val(BS["lt_debt"], c, stmt.long_term_debt)
        val(BS["dt_liab"], c, stmt.deferred_tax_liabilities)
        val(BS["other_ncl"], c, stmt.other_non_current_liabilities)

        val(BS["share_cap"], c, stmt.share_capital)
        val(BS["reserves"], c, stmt.reserves_and_surplus)
        val(BS["mi"], c, stmt.minority_interest)

        # Formulas
        fml(BS["total_ca"], c,
            sum_range(cx, BS["cash"], BS["other_ca"]), sty.num_sub)
        fml(BS["net_fa"], c,
            net_fixed_assets(BS["gross_fa"], BS["acc_dep"], cx), sty.num_sub)
        fml(BS["total_nca"], c,
            sum_range(cx, BS["net_fa"], BS["other_nca"]), sty.num_sub)
        fml(BS["total_assets"], c,
            total_assets(BS["total_ca"], BS["total_nca"], cx), sty.num_sub)
        fml(BS["total_cl"], c,
            sum_range(cx, BS["st_borr"], BS["other_cl"]), sty.num_sub)
        fml(BS["total_ncl"], c,
            sum_range(cx, BS["lt_debt"], BS["other_ncl"]), sty.num_sub)
        fml(BS["total_liab"], c,
            total_liabilities(BS["total_cl"], BS["total_ncl"], cx), sty.num_sub)
        fml(BS["total_equity"], c,
            sum_range(cx, BS["share_cap"], BS["mi"]), sty.num_sub)
        fml(BS["total_le"], c,
            total_liabilities_and_equity(BS["total_liab"], BS["total_equity"], cx),
            sty.num_sub)

        # Balance check (green/red)
        bc = balance_check(BS["total_assets"], BS["total_le"], cx)
        bc_fmt = sty.pass_fmt  # will show "BALANCED" or "ERROR"
        ws.write_formula(BS["balance_check"] - 1, c, bc, bc_fmt)

        fml(BS["wc"], c, working_capital(BS["total_ca"], BS["total_cl"], cx))
        fml(BS["net_debt"], c,
            net_debt(BS["lt_debt"], BS["st_borr"], BS["cash"], BS["sti"], cx))

    return ws


# ── Sheet: Cash Flow ──────────────────────────────────────────────────────────

CF = {
    "header":     1,
    # Operating
    "ops_hdr":    2,
    "net_income": 3,
    "da":         4,
    "wc_chg":     5,
    "other_ops":  6,
    "cfo":        7,
    # Investing
    "inv_hdr":    9,
    "capex":      10,
    "asset_sale": 11,
    "acquisit":   12,
    "invest_net": 13,
    "cfi":        14,
    # Financing
    "fin_hdr":    16,
    "debt_raised":17,
    "debt_repaid":18,
    "dividends":  19,
    "sh_issue":   20,
    "buyback":    21,
    "cff":        22,
    # Summary
    "sum_hdr":    24,
    "net_change": 25,
    "open_cash":  26,
    "close_cash": 27,
    "fcf":        28,
    "cf_check":   30,
}


def _build_cf(wb: xlsxwriter.Workbook, sty: StyleBook,
              statements: List[CashFlowStatement], years: List[int]):
    ws = wb.add_worksheet(SH_CF)
    ws.freeze_panes(2, 1)
    ws.hide_gridlines(2)
    ws.set_column(0, 0, 32)

    data_cols = _data_cols(years)
    for i, yr in enumerate(years):
        ws.set_column(data_cols[i], data_cols[i], 14)
        ws.write(0, data_cols[i], str(yr), sty.col_header)

    def lbl(row: int, text: str, fmt=None):
        ws.write(row - 1, 0, text, fmt or sty.line_label)

    def val(row: int, col_idx: int, value, fmt=None):
        _write_val(ws, row - 1, col_idx, value, fmt or sty.num)

    def fml(row: int, col_idx: int, formula: str, fmt=None):
        ws.write_formula(row - 1, col_idx, formula, fmt or sty.num)

    def xc(col_idx: int) -> str:
        return col_letter(col_idx + 1)

    ws.write(CF["header"] - 1, 0, "CASH FLOW STATEMENT", sty.col_header)

    lbl(CF["ops_hdr"], "OPERATING ACTIVITIES", sty.section_label)
    lbl(CF["net_income"], "Net Income / PAT")
    lbl(CF["da"], "Add: Depreciation & Amortisation")
    lbl(CF["wc_chg"], "Changes in Working Capital")
    lbl(CF["other_ops"], "Other Operating Adjustments")
    lbl(CF["cfo"], "CASH FROM OPERATIONS (CFO)", sty.subtotal_label)

    lbl(CF["inv_hdr"], "INVESTING ACTIVITIES", sty.section_label)
    lbl(CF["capex"], "Capital Expenditure (Capex)")
    lbl(CF["asset_sale"], "Proceeds from Asset Sales")
    lbl(CF["acquisit"], "Acquisitions")
    lbl(CF["invest_net"], "Net Investments")
    lbl(CF["cfi"], "CASH FROM INVESTING (CFI)", sty.subtotal_label)

    lbl(CF["fin_hdr"], "FINANCING ACTIVITIES", sty.section_label)
    lbl(CF["debt_raised"], "Debt Raised")
    lbl(CF["debt_repaid"], "Debt Repaid")
    lbl(CF["dividends"], "Dividends Paid")
    lbl(CF["sh_issue"], "Share Issuance")
    lbl(CF["buyback"], "Share Buyback")
    lbl(CF["cff"], "CASH FROM FINANCING (CFF)", sty.subtotal_label)

    lbl(CF["sum_hdr"], "SUMMARY", sty.section_label)
    lbl(CF["net_change"], "Net Change in Cash", sty.subtotal_label)
    lbl(CF["open_cash"], "Opening Cash Balance")
    lbl(CF["close_cash"], "Closing Cash Balance", sty.subtotal_label)
    lbl(CF["fcf"], "FREE CASH FLOW (FCF)", sty.subtotal_label)
    lbl(CF["cf_check"], "CF Reconciliation Check", sty.section_label)

    for i, (yr, stmt) in enumerate(zip(years, statements)):
        c = data_cols[i]
        cx = xc(c)

        val(CF["net_income"], c, stmt.net_income)
        val(CF["da"], c, stmt.depreciation_amortization)
        val(CF["wc_chg"], c, stmt.changes_in_working_capital)
        val(CF["other_ops"], c, stmt.other_operating_adjustments)
        if stmt.cash_from_operations is not None:
            val(CF["cfo"], c, stmt.cash_from_operations, sty.num_sub)
        else:
            fml(CF["cfo"], c,
                f"=SUM({cx}{CF['net_income']}:{cx}{CF['other_ops']})", sty.num_sub)

        val(CF["capex"], c, stmt.capex)
        val(CF["asset_sale"], c, stmt.proceeds_from_asset_sales)
        val(CF["acquisit"], c, stmt.acquisitions)
        val(CF["invest_net"], c, stmt.investments_net)
        if stmt.cash_from_investing is not None:
            val(CF["cfi"], c, stmt.cash_from_investing, sty.num_sub)
        else:
            fml(CF["cfi"], c,
                f"=SUM({cx}{CF['capex']}:{cx}{CF['invest_net']})", sty.num_sub)

        val(CF["debt_raised"], c, stmt.debt_raised)
        val(CF["debt_repaid"], c, stmt.debt_repaid)
        val(CF["dividends"], c, stmt.dividends_paid)
        val(CF["sh_issue"], c, stmt.share_issuance)
        val(CF["buyback"], c, stmt.share_buyback)
        if stmt.cash_from_financing is not None:
            val(CF["cff"], c, stmt.cash_from_financing, sty.num_sub)
        else:
            fml(CF["cff"], c,
                f"=SUM({cx}{CF['debt_raised']}:{cx}{CF['buyback']})", sty.num_sub)

        fml(CF["net_change"], c,
            net_change_in_cash(CF["cfo"], CF["cfi"], CF["cff"], cx), sty.num_sub)
        val(CF["open_cash"], c, stmt.opening_cash)
        fml(CF["close_cash"], c,
            closing_cash(CF["open_cash"], CF["net_change"], cx), sty.num_sub)
        fml(CF["fcf"], c,
            free_cash_flow(CF["cfo"], CF["capex"], cx), sty.num_sub)

        # CF reconciliation check
        bs_cash_row = BS["cash"]
        fml(CF["cf_check"], c,
            f"=IF(ABS({cx}{CF['close_cash']}-'{SH_BS}'!{cx}{bs_cash_row})<1,"
            f'"OK","CF RECONCILIATION ERROR")',
            sty.pass_fmt)

    return ws


# ── Sheet: Ratios ─────────────────────────────────────────────────────────────

def _build_ratios(wb: xlsxwriter.Workbook, sty: StyleBook, years: List[int]):
    ws = wb.add_worksheet(SH_RT)
    ws.freeze_panes(2, 1)
    ws.hide_gridlines(2)
    ws.set_column(0, 0, 36)

    data_cols = _data_cols(years)
    for i, yr in enumerate(years):
        ws.set_column(data_cols[i], data_cols[i], 14)
        ws.write(0, data_cols[i], str(yr), sty.col_header)

    ws.write(0, 0, "FINANCIAL RATIOS", sty.col_header)

    def lbl(row: int, text: str, fmt=None):
        ws.write(row - 1, 0, text, fmt or sty.line_label)

    def xr(sheet: str, row_key: int, col_idx: int) -> str:
        """Cross-sheet reference using row number from row map."""
        cx = col_letter(col_idx + 1)
        return f"'{sheet}'!{cx}{row_key}"

    def fml_pct(row: int, col_idx: int, formula: str):
        ws.write_formula(row - 1, col_idx, formula, sty.pct)

    def fml_num(row: int, col_idx: int, formula: str):
        ws.write_formula(row - 1, col_idx, formula, sty.num)

    # Row layout
    R = {
        "liq_hdr": 2,
        "cr": 3, "qr": 4, "cash_r": 5, "wc_days": 6,
        "prof_hdr": 8,
        "gross_m": 9, "ebitda_m": 10, "ebit_m": 11, "net_m": 12,
        "roe": 13, "roa": 14, "roce": 15,
        "lev_hdr": 17,
        "de": 18, "nd_ebitda": 19, "int_cov": 20, "debt_ebitda": 21,
        "eff_hdr": 23,
        "asset_to": 24, "inv_to": 25, "dio": 26, "dso": 27, "dpo": 28, "ccc": 29,
        "pershare_hdr": 31,
        "eps_r": 32, "bvps": 33, "fcf_per": 34, "dps_r": 35,
        "dupont_hdr": 37,
        "dp_nm": 38, "dp_at": 39, "dp_em": 40, "dp_roe": 41,
    }

    # Labels
    lbl(R["liq_hdr"], "A.  LIQUIDITY RATIOS", sty.section_label)
    lbl(R["cr"],      "Current Ratio (x)")
    lbl(R["qr"],      "Quick Ratio (x)")
    lbl(R["cash_r"],  "Cash Ratio (x)")
    lbl(R["wc_days"], "Working Capital Days")

    lbl(R["prof_hdr"], "B.  PROFITABILITY RATIOS", sty.section_label)
    lbl(R["gross_m"],  "Gross Margin %")
    lbl(R["ebitda_m"], "EBITDA Margin %")
    lbl(R["ebit_m"],   "EBIT Margin %")
    lbl(R["net_m"],    "Net Profit Margin %")
    lbl(R["roe"],      "Return on Equity (ROE) %")
    lbl(R["roa"],      "Return on Assets (ROA) %")
    lbl(R["roce"],     "Return on Capital Employed (ROCE) %")

    lbl(R["lev_hdr"],    "C.  LEVERAGE RATIOS", sty.section_label)
    lbl(R["de"],         "Debt / Equity Ratio (x)")
    lbl(R["nd_ebitda"],  "Net Debt / EBITDA (x)")
    lbl(R["int_cov"],    "Interest Coverage Ratio (x)")
    lbl(R["debt_ebitda"],"Total Debt / EBITDA (x)")

    lbl(R["eff_hdr"],  "D.  EFFICIENCY RATIOS", sty.section_label)
    lbl(R["asset_to"], "Asset Turnover (x)")
    lbl(R["inv_to"],   "Inventory Turnover (x)")
    lbl(R["dio"],      "Days Inventory Outstanding (DIO)")
    lbl(R["dso"],      "Days Sales Outstanding (DSO)")
    lbl(R["dpo"],      "Days Payable Outstanding (DPO)")
    lbl(R["ccc"],      "Cash Conversion Cycle (CCC)")

    lbl(R["pershare_hdr"], "E.  PER SHARE DATA", sty.section_label)
    lbl(R["eps_r"],    "EPS (Basic)")
    lbl(R["bvps"],     "Book Value Per Share")
    lbl(R["fcf_per"],  "Free Cash Flow Per Share")
    lbl(R["dps_r"],    "Dividends Per Share")

    lbl(R["dupont_hdr"], "F.  DUPONT ANALYSIS (ROE = NM × AT × EM)", sty.section_label)
    lbl(R["dp_nm"],   "Net Margin")
    lbl(R["dp_at"],   "Asset Turnover")
    lbl(R["dp_em"],   "Equity Multiplier (Total Assets / Equity)")
    lbl(R["dp_roe"],  "DuPont ROE (cross-check)", sty.subtotal_label)

    # Formulas per year
    for i, c in enumerate(data_cols):
        # Cross-sheet shorthand
        rev = xr(SH_IS, IS["revenue"], c)
        gp  = xr(SH_IS, IS["gross_profit"], c)
        ebitda = xr(SH_IS, IS["ebitda"], c)
        ebit_v = xr(SH_IS, IS["ebit"], c)
        pat_v  = xr(SH_IS, IS["pat"], c)
        int_v  = xr(SH_IS, IS["interest"], c)
        cogs_v = xr(SH_IS, IS["cogs"], c)
        shares_v = xr(SH_IS, IS["shares"], c)
        dps_v  = xr(SH_IS, IS["dps"], c)

        ca   = xr(SH_BS, BS["total_ca"], c)
        cl   = xr(SH_BS, BS["total_cl"], c)
        inv  = xr(SH_BS, BS["inventory"], c)
        cash_v = xr(SH_BS, BS["cash"], c)
        sti  = xr(SH_BS, BS["sti"], c)
        recv = xr(SH_BS, BS["receivables"], c)
        pay  = xr(SH_BS, BS["payables"], c)
        ta   = xr(SH_BS, BS["total_assets"], c)
        eq   = xr(SH_BS, BS["total_equity"], c)
        ltd  = xr(SH_BS, BS["lt_debt"], c)
        stb  = xr(SH_BS, BS["st_borr"], c)
        wc   = xr(SH_BS, BS["wc"], c)
        nd   = xr(SH_BS, BS["net_debt"], c)

        fcf  = xr(SH_CF, CF["fcf"], c)

        def w_pct(r: int, f: str): fml_pct(r, c, f)
        def w_num(r: int, f: str): fml_num(r, c, f)

        # Liquidity
        w_num(R["cr"],      f"=IFERROR({ca}/{cl},0)")
        w_num(R["qr"],      f"=IFERROR(({ca}-{inv})/{cl},0)")
        w_num(R["cash_r"],  f"=IFERROR(({cash_v}+{sti})/{cl},0)")
        w_num(R["wc_days"], f"=IFERROR({wc}/{rev}*365,0)")

        # Profitability
        w_pct(R["gross_m"],  f"=IFERROR({gp}/{rev},0)")
        w_pct(R["ebitda_m"], f"=IFERROR({ebitda}/{rev},0)")
        w_pct(R["ebit_m"],   f"=IFERROR({ebit_v}/{rev},0)")
        w_pct(R["net_m"],    f"=IFERROR({pat_v}/{rev},0)")
        w_pct(R["roe"],      f"=IFERROR({pat_v}/{eq},0)")
        w_pct(R["roa"],      f"=IFERROR({pat_v}/{ta},0)")
        w_pct(R["roce"],     f"=IFERROR({ebit_v}/({ta}-{cl}),0)")

        # Leverage
        total_debt = f"({ltd}+{stb})"
        w_num(R["de"],         f"=IFERROR({total_debt}/{eq},0)")
        w_num(R["nd_ebitda"],  f"=IFERROR({nd}/{ebitda},0)")
        w_num(R["int_cov"],    f"=IFERROR({ebit_v}/{int_v},0)")
        w_num(R["debt_ebitda"],f"=IFERROR({total_debt}/{ebitda},0)")

        # Efficiency
        w_num(R["asset_to"], f"=IFERROR({rev}/{ta},0)")
        w_num(R["inv_to"],   f"=IFERROR({cogs_v}/{inv},0)")
        w_num(R["dio"],      f"=IFERROR({inv}/{cogs_v}*365,0)")
        w_num(R["dso"],      f"=IFERROR({recv}/{rev}*365,0)")
        w_num(R["dpo"],      f"=IFERROR({pay}/{cogs_v}*365,0)")
        # CCC cell references (same sheet)
        dio_ref = f"{col_letter(c+1)}{R['dio']}"
        dso_ref = f"{col_letter(c+1)}{R['dso']}"
        dpo_ref = f"{col_letter(c+1)}{R['dpo']}"
        w_num(R["ccc"], f"={dio_ref}+{dso_ref}-{dpo_ref}")

        # Per Share
        w_num(R["eps_r"],   f"=IFERROR({pat_v}/{shares_v},0)")
        w_num(R["bvps"],    f"=IFERROR({eq}/{shares_v},0)")
        w_num(R["fcf_per"], f"=IFERROR({fcf}/{shares_v},0)")
        w_num(R["dps_r"],   f"={dps_v}")

        # DuPont
        nm_ref  = f"{col_letter(c+1)}{R['dp_nm']}"
        at_ref  = f"{col_letter(c+1)}{R['dp_at']}"
        em_ref  = f"{col_letter(c+1)}{R['dp_em']}"
        w_pct(R["dp_nm"], f"=IFERROR({pat_v}/{rev},0)")
        w_num(R["dp_at"], f"=IFERROR({rev}/{ta},0)")
        w_num(R["dp_em"], f"=IFERROR({ta}/{eq},0)")
        w_pct(R["dp_roe"], f"={nm_ref}*{at_ref}*{em_ref}")

    return ws


# ── Sheet: Verification ───────────────────────────────────────────────────────

def _build_verification(wb: xlsxwriter.Workbook, sty: StyleBook, years: List[int]):
    ws = wb.add_worksheet(SH_VR)
    ws.hide_gridlines(2)
    ws.set_column(0, 0, 40)

    data_cols = _data_cols(years)
    for i, yr in enumerate(years):
        ws.set_column(data_cols[i], data_cols[i], 16)
        ws.write(0, data_cols[i], str(yr), sty.col_header)

    ws.write(0, 0, "VERIFICATION & QUALITY CHECKS", sty.col_header)

    sections = [
        # (row, label, formula_template)
        (2, "1. BALANCE SHEET EQUATION", None),
        (3, "   Total Assets", f"='{SH_BS}'!{{c}}{BS['total_assets']}"),
        (4, "   Total Liabilities + Equity", f"='{SH_BS}'!{{c}}{BS['total_le']}"),
        (5, "   Difference", f"=B3-B4"),
        (6, "   STATUS",
         f'=IF(ABS({{c}}3-{{c}}4)<1,"✓ PASS","✗ FAIL")'),
        (8, "2. CASH FLOW RECONCILIATION", None),
        (9, "   Net Change in Cash (CF Statement)", f"='{SH_CF}'!{{c}}{CF['net_change']}"),
        (10, "  Closing - Opening (Balance Sheet)", f"='{SH_CF}'!{{c}}{CF['close_cash']}-'{SH_CF}'!{{c}}{CF['open_cash']}"),
        (11, "  Difference", "={c}9-{c}10"),
        (12, "  STATUS",
         '=IF(ABS({c}9-{c}10)<1,"✓ PASS","✗ FAIL")'),
        (14, "3. PAT CONSISTENCY (IS vs CF)", None),
        (15, "   PAT (Income Statement)", f"='{SH_IS}'!{{c}}{IS['pat']}"),
        (16, "   Net Income (Cash Flow)", f"='{SH_CF}'!{{c}}{CF['net_income']}"),
        (17, "   Difference", "={c}15-{c}16"),
        (18, "   STATUS",
         '=IF(ABS({c}15-{c}16)/{c}15<0.05,"✓ PASS","⚠ WARNING >5%")'),
    ]

    for row, label, _ in sections:
        ws.write(row - 1, 0, label,
                 sty.section_label if label[0].isdigit() else sty.line_label)

    for i, c in enumerate(data_cols):
        cx = col_letter(c + 1)

        # BS check
        ws.write_formula(2, c, f"='{SH_BS}'!{cx}{BS['total_assets']}", sty.num)
        ws.write_formula(3, c, f"='{SH_BS}'!{cx}{BS['total_le']}", sty.num)
        ws.write_formula(4, c, f"={cx}3-{cx}4", sty.num)
        ws.write_formula(5, c,
            f'=IF(ABS({cx}3-{cx}4)<1,"✓ PASS","✗ FAIL")',
            sty.pass_fmt)

        # CF reconciliation
        ws.write_formula(8, c, f"='{SH_CF}'!{cx}{CF['net_change']}", sty.num)
        ws.write_formula(9, c,
            f"='{SH_CF}'!{cx}{CF['close_cash']}-'{SH_CF}'!{cx}{CF['open_cash']}",
            sty.num)
        ws.write_formula(10, c, f"={cx}9-{cx}10", sty.num)
        ws.write_formula(11, c,
            f'=IF(ABS({cx}9-{cx}10)<1,"✓ PASS","✗ FAIL")',
            sty.pass_fmt)

        # PAT consistency
        ws.write_formula(14, c, f"='{SH_IS}'!{cx}{IS['pat']}", sty.num)
        ws.write_formula(15, c, f"='{SH_CF}'!{cx}{CF['net_income']}", sty.num)
        ws.write_formula(16, c, f"={cx}15-{cx}16", sty.num)
        ws.write_formula(17, c,
            f'=IF(IFERROR(ABS({cx}15-{cx}16)/ABS({cx}15),1)<0.05,'
            f'"✓ PASS","⚠ WARNING >5%")',
            sty.warn_fmt)

    return ws


# ── Sheet: Settings ───────────────────────────────────────────────────────────

def _build_settings(wb: xlsxwriter.Workbook, sty: StyleBook):
    ws = wb.add_worksheet(SH_ST)
    ws.hide_gridlines(2)
    ws.set_column(0, 0, 36)
    ws.set_column(1, 1, 16)
    ws.set_column(2, 2, 40)

    ws.write(0, 0, "SETTINGS & VALUATION ASSUMPTIONS", sty.col_header)
    ws.write(0, 1, "Value", sty.col_header)
    ws.write(0, 2, "Notes", sty.col_header)

    rows = [
        (2, "Risk-Free Rate (Rf)", RISK_FREE_RATE, "Indian 10Y G-Sec yield — update as needed"),
        (3, "Equity Risk Premium (ERP)", EQUITY_RISK_PREMIUM, "Damodaran India ERP estimate"),
        (4, "Beta (β)", DEFAULT_BETA, "Company beta vs Nifty 50 — update for target company"),
        (5, "Corporate Tax Rate", CORPORATE_TAX_RATE, "Indian base rate 25%"),
        (6, "Terminal Growth Rate (g)", TERMINAL_GROWTH_RATE, "Long-run GDP growth assumption"),
        (7, "Pre-Tax Cost of Debt", 0.09, "Interest Expense / Average Debt — update"),
    ]

    for row, label, val, note in rows:
        ws.write(row - 1, 0, label, sty.line_label)
        ws.write_number(row - 1, 1, val, sty.input_cell)
        ws.write(row - 1, 2, note, sty.line_label)

    # Computed values
    ws.write(7, 0, "Cost of Equity (CAPM)", sty.subtotal_label)
    ws.write_formula(7, 1, "=B2+B4*B3", sty.pct)
    ws.write(7, 2, "= Rf + β × ERP", sty.line_label)

    ws.write(8, 0, "After-Tax Cost of Debt", sty.subtotal_label)
    ws.write_formula(8, 1, "=B7*(1-B5)", sty.pct)
    ws.write(8, 2, "= Pre-Tax Cost of Debt × (1 - Tax Rate)", sty.line_label)

    ws.write(10, 0, "Market Cap (₹ Cr) — Input", sty.line_label)
    ws.write_blank(10, 1, sty.input_cell_num)
    ws.write(10, 2, "Enter current market capitalisation", sty.line_label)

    ws.write(11, 0, "Current Share Price — Input", sty.line_label)
    ws.write_blank(11, 1, sty.input_cell_num)

    ws.write(12, 0, "Shares Outstanding (pull from IS)", sty.subtotal_label)
    ws.write_formula(12, 1,
        f"=IFERROR('{SH_IS}'!{col_letter(data_cols[-1]+1)}{IS['shares']},\"\")",
        sty.num_int)

    return ws


# We need data_cols[-1] at module level for Settings — expose via build_workbook closure
_last_data_col = 1   # fallback; overwritten in build_workbook


# ── Public Entry Point ────────────────────────────────────────────────────────

def build_workbook(financial_data: FinancialData, output_path: Optional[str] = None) -> str:
    """
    Build the full Excel workbook from FinancialData.
    Returns the path to the generated .xlsx file.
    """
    years = financial_data.sorted_years()
    if not years:
        raise ValueError("FinancialData has no fiscal_years — cannot build workbook.")

    if output_path is None:
        safe_name = financial_data.company_name.replace(" ", "_").replace("/", "-")
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_path = str(EXCEL_DIR / f"{safe_name}_{ts}.xlsx")

    global data_cols, _last_data_col
    data_cols = _data_cols(years)
    _last_data_col = data_cols[-1]

    log.info(f"Building Excel workbook → {output_path}")

    wb = xlsxwriter.Workbook(output_path)
    sty = StyleBook(wb)

    # Align statements to years (insert None-filled stubs for missing years)
    def align(stmts, cls):
        by_year = {s.fiscal_year: s for s in stmts}
        return [by_year.get(yr, cls(fiscal_year=yr)) for yr in years]

    income_stmts = align(financial_data.income_statements, IncomeStatement)
    balance_sheets = align(financial_data.balance_sheets, BalanceSheet)
    cash_flows = align(financial_data.cash_flow_statements, CashFlowStatement)

    from agents.valuation_builder import (
        build_comps_sheet,
        build_dcf_sheet,
        build_ddm_sheet,
        build_wacc_sheet,
    )
    from agents.charts_builder import build_charts_sheet

    _build_cover(wb, sty, financial_data.company_name, years)
    _build_is(wb, sty, income_stmts, years)
    _build_bs(wb, sty, balance_sheets, years)
    _build_cf(wb, sty, cash_flows, years)
    _build_ratios(wb, sty, years)
    _build_verification(wb, sty, years)
    _build_settings(wb, sty)
    build_wacc_sheet(wb, sty, years)
    build_dcf_sheet(wb, sty, years)
    build_ddm_sheet(wb, sty, years)
    build_comps_sheet(wb, sty, years)
    build_charts_sheet(wb, sty, years)

    wb.close()
    log.info(f"Workbook saved: {output_path}")
    return output_path
